//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carton
    {
        public int CartonID { get; set; }
        public string ASNNo { get; set; }
        public string BarCodeNumber { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PreviousPlace { get; set; }
        public string RecentPlace { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CratedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
