//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartonBarCodeDetail
    {
        public int CartonBarCodeDetailsID { get; set; }
        public int ASNProductDetailsID { get; set; }
        public string BarCodeNo { get; set; }
        public string CartonID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Location { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AdvanceShippingProductDetail AdvanceShippingProductDetail { get; set; }
    }
}
