//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdvanceShipping> AdvanceShippings { get; set; }
        public DbSet<AdvanceShippingProductDetail> AdvanceShippingProductDetails { get; set; }
        public DbSet<BrandMaster> BrandMasters { get; set; }
        public DbSet<CartonBarCodeDetail> CartonBarCodeDetails { get; set; }
        public DbSet<Carton> Cartons { get; set; }
        public DbSet<CategoryMaster> CategoryMasters { get; set; }
        public DbSet<CountryMaster> CountryMasters { get; set; }
        public DbSet<CurrencyMaster> CurrencyMasters { get; set; }
        public DbSet<CustomerMaster> CustomerMasters { get; set; }
        public DbSet<CustomerSKU> CustomerSKUs { get; set; }
        public DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public DbSet<PickingList> PickingLists { get; set; }
        public DbSet<ProductMaster> ProductMasters { get; set; }
        public DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public DbSet<ReceiveMainDetail> ReceiveMainDetails { get; set; }
        public DbSet<ReceiveProductDetail> ReceiveProductDetails { get; set; }
        public DbSet<SalesOrder> SalesOrders { get; set; }
        public DbSet<StockMaster> StockMasters { get; set; }
        public DbSet<StoreMaster> StoreMasters { get; set; }
        public DbSet<SupplierBrand> SupplierBrands { get; set; }
        public DbSet<SupplierMaster> SupplierMasters { get; set; }
        public DbSet<UOMMaster> UOMMasters { get; set; }
    }
}
