//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickingList
    {
        public int PLID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string ItemCode { get; set; }
        public string BarCodeID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
