//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public ProductMaster()
        {
            this.AdvanceShippingProductDetails = new HashSet<AdvanceShippingProductDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }
    
        public int ProductID { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public string MFBarcode { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> UOMID { get; set; }
        public string DiLength { get; set; }
        public string DiBreadth { get; set; }
        public string DiHeight { get; set; }
        public string DiWeight { get; set; }
        public string SpLength { get; set; }
        public string SpBreadth { get; set; }
        public string SpHeight { get; set; }
        public string SpWeight { get; set; }
        public Nullable<int> QPC { get; set; }
        public Nullable<decimal> BasicPC { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<decimal> SRP { get; set; }
        public Nullable<int> ShelfLife { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<AdvanceShippingProductDetail> AdvanceShippingProductDetails { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    }
}
