//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierMaster
    {
        public SupplierMaster()
        {
            this.AdvanceShippings = new HashSet<AdvanceShipping>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string BuildingName { get; set; }
        public string Street { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<AdvanceShipping> AdvanceShippings { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
